apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: todo
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: my-cluster-kafka-bootstrap:9092
  - name: authType
    value: none
  - name: consumerGroup
    value: dapr-group
  - name: clientID
    value: dapr-kafka-client
  - name: disableAutoCommit
    value: "false"
  - name: maxMessageBytes
    value: 1048576
  - name: consumeRetryInterval
    value: 200ms